### ISSUE TITLE
Input field is not always adjusted by plugin

### ISSUE THREAD

**Issue by gziolo** [fdeschenes/bootstrap-tag#1]
Great plugin, works perfectly fine, but there is one edge case when it loads too soon. It is caused by this line:
https://github.com/fdeschenes/bootstrap-tag/blob/master/js/bootstrap-tag.js#L186
Changing load event to jQuery DOM ready solves issue. My fix was as follows

``` javascript
 $(function () {
```

This is probably caused by the fact that I'm embeding my JS files at the bottom of header. Which is not perfect solution, but due to some legace code I don't have much choice at the moment.

**Comment by harshmadhani** [comment]
@gziolo : You can solve this issue by using the bootstrap-tag.css file in the docs folder. This helps to maintain my regular code rather than adding the following code :  

```
$(function(){
```

**Comment by fdeschenes** [comment]
Sorry for not replying sooner – I didn't see this until now.

I have a feeling that your issue is caused by one of your page's assets taking a long time to load (or not loading at all).  The `load` event I use will wait for all files references by your site to have been downloaded and processed by the browser.  Using `$(function() {` appears to solve that because it causes the script to run as soon as the DOM has loaded.

I'll reconsider using jQuery's `ready` event instead of the built-in `load` if that's still an issue for you.
